### ISSUE TITLE
Enable JuliaRegistrator and TagBot

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#102]
@c42f / @andyferris, I requested permission to install JuliaTeam Registrator and TagBot on this repo a while back, but it hasn't been granted yet. Could you grant permission so I can release a new version?

**Comment by c42f** [comment]
I'm not a member of the organization any longer so I lost my permission to do this a while back. @andyferris over to you!

**Comment by andyferris** [comment]
Done! Thanks @tkoolen ❤️

**Comment by tkoolen** [comment]
Thank you!
