### ISSUE TITLE
`StaticArrays` compat entry

### ISSUE THREAD

**Issue by goretkin** [FugroRoames/Rotations.jl#105]
https://github.com/FugroRoames/Rotations.jl/commit/91572b9d28c7c0cee6e5d5b3be704f0abfc76529 seems to have restricted `StaticArrays` to a single version, which doesn't seem intentional.

**Comment by c42f** [comment]
I do suspect this was unintentional and we could add StaticArrays 0.11 and 0.12 in there. Tests seem to pass with 0.12.1.

(Looking at this I noticed https://github.com/JuliaArrays/StaticArrays.jl/issues/700 but thankfully that only seems to apply to latest StaticArrays master...)

**Comment by tkoolen** [comment]
Apologies!
