### ISSUE TITLE
Branch and tag for 0.5

### ISSUE THREAD

**Issue by andyferris** [FugroRoames/Rotations.jl#11]
@awbsmith, @c42f

I've been slowly updating a bunch of other packages to work with StaticArrays and the related branch of Rotations. I'm thinking of tagging a (Julia 0.5+ only) release of Rotations, say version 0.3.0, that will go on that branch. We can continue tagging 0.2.x releases for Julia 0.4 using the master branch and when we are all using Julia 0.5, we can merge the static_arrays branch with master.

Is everyone OK with this?

**Comment by awbsmith** [comment]
That works for me

**Comment by andyferris** [comment]
Are you using/planning to use 0.2.0 at some point Andrew? I thought I saw a commit about that but now I don't see the tag...

**Comment by c42f** [comment]
If we're going to switch to 0.5 very soon anyway, perhaps it's worth doing the reverse - creating a 0.4 branch for backporting a few bits and pieces as required, and go forward with master as 0.5.

Really up to you @awbsmith.

**Comment by andyferris** [comment]
Decision?

**Comment by awbsmith** [comment]
master as 0.5!
