### ISSUE TITLE
A "lazy" 2D rotation type

### ISSUE THREAD

**Issue by andyferris** [FugroRoames/Rotations.jl#14]
A 2D rotation parameterized by an angle would be welcome. This would go in the "angle-axis" family.

Internally the new type could store the angle, or it could optionally also store the cos and sin of the angle for efficiency in application to multiple points. Would only save one value compared to `RotMatrix{2}` and be marginally faster, but it would be guaranteed to be a parity-preserving rotation.

**Comment by juliohm** [comment]
Thanks for this very nice package! I am wondering if I can use it right away to define ellipsoid-like norms in one of my packages...

How is the support for rotations on 2D vectors? Can you confirm that the current API only applies to vectors in 3D space?

**Comment by andyferris** [comment]
We have `Rotation{2}` as an abstract type for 2D rotations. I think the only concrete type right now is `RotMatrix{2}` which is a 2D static matrix with fast inverse (via transpose). 

It should work well for ellipsoidal norms.

**Comment by juliohm** [comment]
That sounds like exactly what I need, thanks.
