### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#15]
I'd greatly appreciate a release with the type changes made in https://github.com/FugroRoames/Rotations.jl/pull/13. Thanks!

**Comment by andyferris** [comment]
Good idea! I didn't realise this hadn't happened

**Comment by andyferris** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/7196

**Comment by andyferris** [comment]
And again, https://github.com/JuliaLang/METADATA.jl/pull/7216

**Comment by tkoolen** [comment]
Awesome, thanks!
