### ISSUE TITLE
On Julia v0.6 the size of rotations are not known (due to StaticArrays)

### ISSUE THREAD

**Issue by zsoerenm** [FugroRoames/Rotations.jl#24]
I still get a size error, although I checked out the latest Rotations.jl
```
julia> Pkg.status()
- Rotations                     0.3.5              master
```

The error is the following:
```
ERROR: The size of type `Rotations.RotXYZ{Float64}` is not known.

If you were trying to construct (or `convert` to) a `StaticArray` you
may need to add the size explicitly as a type parameter so its size is
inferrable to the Julia compiler (or performance would be terrible). For
example, you might try

    m = zeros(3,3)
    SMatrix(m)      # this error
    SMatrix{3,3}(m) # correct - size is inferrable

Stacktrace:
 [1] StaticArrays.Size(::Type{Rotations.RotXYZ{Float64}}) at /home/zorn/.julia/v0.6/StaticArrays/src/traits.jl:42
 [2] size(::Type{Rotations.RotXYZ{Float64}}) at /home/zorn/.julia/v0.6/StaticArrays/src/abstractarray.jl:7
 [3] *(...) at /home/zorn/.julia/v0.6/StaticArrays/src/matrix_multiply.jl:199

```

**Comment by andyferris** [comment]
Just to double-check, which version of `StaticArrays` are you using?

**Comment by zsoerenm** [comment]
```
julia> Pkg.status()
- StaticArrays                  0.3.0
```

BTW this is julia v0.6, but that is not the problem, is it?

**Comment by andyferris** [comment]
Oh, yes that is *definitely* a problem.

See https://github.com/JuliaArrays/StaticArrays.jl/issues/113 and https://github.com/JuliaArrays/StaticArrays.jl/issues/109. In particular, the problem in the latter means that *any* type defined after *StaticArrays* is imported will not function correctly. We are working hard to rewrite *StaticArrays* to work with the new compiler (such extremely low-level packages are susceptible to subtle compiler changes that occur with new versions of Julia) but it's a non-trivial amount of work to do in spare time, so it might be another week or two before the v0.6 version is fully up-and-running, sorry.

(I'll edit the title and leave the issue open until *StaticArrays* is fixed).

**Comment by tkoolen** [comment]
Fixed by https://github.com/FugroRoames/Rotations.jl/pull/25.

**Comment by c42f** [comment]
Thanks!
