### ISSUE TITLE
Roll/pitch/yaw correspond only to RotXYZ

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#26]
Roll/pitch/yaw refer specifically to the angles of a `RotXYZ` (see e.g. https://en.wikipedia.org/wiki/Euler_angles#Conventions_2.), but currently roll/pitch/yaw keyword constructors are defined for all Tait-Bryant types.

**Comment by andyferris** [comment]
We've been using this as a convenience constructor, which enables you to apply roll, pitch and yaw in a non-standard order (and obviously get a different rotation depending on the order). We've found it quite useful.

Do you find this to be too confusing/problematic?

**Comment by tkoolen** [comment]
I suppose it doesn't hurt to have them around since you're calling the constructor of a specific rotation type anyway, it's just nonstandard. Feel free to close if you don't want to fix it.

**Comment by andyferris** [comment]
OK, thanks.

**Comment by andyferris** [comment]
I think the exact point of these constructors is to allow you to do something sensible when someone else gives you some non-standard parametization of a rotation.

**Comment by c42f** [comment]
I'm not sure I agree with you here Andy.  Do we really need the nonstandard ones, and do they make any sense?  Maybe what would be more useful for generic code would be `thetaX` `thetaY` and `thetaZ` keywords?
