### ISSUE TITLE
Warnings on Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [FugroRoames/Rotations.jl#27]
>WARNING: deprecated syntax "abstract Rotation{N,T}<:StaticMatrix{T}" at /home/juliohm/.julia/v0.6/Rotations/src/core_types.jl:8.
Use "abstract type Rotation{N,T}<:StaticMatrix{T} end" instead.

>WARNING: deprecated syntax "inner constructor Quat(...) around /home/juliohm/.julia/v0.6/Rotations/src/quaternion_types.jl:21".
Use "Quat{T}(...) where T" instead.

>WARNING: deprecated syntax "inner constructor AngleAxis(...) around /home/juliohm/.julia/v0.6/Rotations/src/angleaxis_types.jl:22".
Use "AngleAxis{T}(...) where T" instead.

**Comment by tkoolen** [comment]
Those are fixed on master. Julia 0.6 is not supported on the latest released version. @c42f, @andyferris, OK to tag a new version? I can do it tomorrow.

**Comment by c42f** [comment]
Sure, go for it!

**Comment by andyferris** [comment]
FYI there is another breaking change coming to StaticArrays (putting the size in `StaticArray`) so it's up to you if we wait for that...

**Comment by c42f** [comment]
Right, if you want to release, it's worth fixing REQUIRE first to specify both an upper and lower bound on the StaticArrays version.

**Comment by tkoolen** [comment]
Fixed by release of Rotations 0.4.0.
