### ISSUE TITLE
Use internal inverse function instead of Base.inv

### ISSUE THREAD

**Issue by juliohm** [FugroRoames/Rotations.jl#274]
Apparently `Base.inv` is only intended for multiplicative inverses:

```julia
 inv(x)


  Return the multiplicative inverse of x, such that x*inv(x) or inv(x)*x yields
  one(x) (the multiplicative identity) up to roundoff errors.

  If x is a number, this is essentially the same as one(x)/x, but for some types
  inv(x) may be slightly more efficient.
```

We recently learned about InverseFunctions.jl, which introduces a `inverse` function for inverse functions. Rotations.jl could use the same function or add an internal name `inverse` that is not exported by default.

We are fixing all our packages to avoid the misuse of `Base.inv`.

**Comment by hyrodium** [comment]
`Base.inv` is an inverse operation about the binary operator `*`, and `InverseFunctions.inverse` is an inverse operation about the binary operator `∘` (`\circle`).

The current usage in this package `inv(::Rotation)` is related to `*`, so we don't have to switch to `InverseFunctions.inverse`.

```julia
julia> using Rotations

julia> r = QuatRotation(2,1,0,0)
3×3 QuatRotation{Float64} with indices SOneTo(3)×SOneTo(3)(QuaternionF64(0.894427, 0.447214, 0.0, 0.0)):
 1.0  0.0   0.0
 0.0  0.6  -0.8
 0.0  0.8   0.6

julia> r * inv(r)
3×3 QuatRotation{Float64} with indices SOneTo(3)×SOneTo(3)(QuaternionF64(1.0, 0.0, 0.0, 0.0)):
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

**Comment by juliohm** [comment]
It makes sense if we think of rotations as matrix multiplication always.
Feel free to close the issue if inv is intended.

Em ter., 7 de nov. de 2023 00:09, Yuto Horikawa ***@***.***>
escreveu:
