### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#40]
I'd like to tag a new version; is that OK?

Proposed release notes:
* Require Julia 0.6.0-pre (#35)
* add `RotMatrix2`, `RotMatrix3` type aliases (#36)
* add option to skip renormalization of `AngleAxis` and `Quat` (#37)
* Fix performance issues introduced in #32 due to missing `Tuple` constructor specializations (#38, #39)

**Comment by c42f** [comment]
Now that 0.6 is out we can drop the `-pre` I think. Other than that, I think we're good to go.

Thanks a lot for making the release notes.

**Comment by tkoolen** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/10589.
