### ISSUE TITLE
Enable FemtoCleaner?

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#42]
https://github.com/Keno/FemtoCleaner.jl

https://discourse.julialang.org/t/ann-femtocleaner-our-newest-robot-intern/5340

I installed it on my fork of Rotations; here's what it will do: https://github.com/tkoolen/Rotations.jl/pull/1.

**Comment by c42f** [comment]
Looks useful to me, I think we should enable it.  Interesting that it breaks a stylistic convention we've been using (at least in `Rotations`), which is to always wrap the `T` in `where {T}` with curlies, even when there's a single type argument.

**Comment by c42f** [comment]
I opened an issue about this: https://github.com/JuliaComputing/Deprecations.jl/issues/1

Maybe it'll get shot down, but that's ok :-)

**Comment by tkoolen** [comment]
I don't consider the curly braces thing a showstopper BTW. So enable it?

**Comment by c42f** [comment]
Sure, go for it.

**Comment by tkoolen** [comment]
I would have, but I don't have permissions to access 'Settings'.

**Comment by c42f** [comment]
Ah right, sorry about that.  I'll just add it.
