### ISSUE TITLE
rotation_angle(::Quaternion)

### ISSUE THREAD

**Issue by awbsmith** [FugroRoames/Rotations.jl#6]
There's currently an issue that
``` rotation_angle(q::Quaternion)  = 2*acos(q.s) ```
doesn't check / force q.s into the [-1, 1] range.  This broke another package with rounding errors putting q.s out of range, causing acos to throw.  Some options:

1) always renormalize the quaternion (but it'll cause more rounding)
2) use max / min (but this is gammy for non-unit quaternions)
3) leave it to the user (but this sucks)
4) voodoo loosening of the acos range ([-1-1e9, 1+1e-9] or something?)

I don't really like any of these options.   The Quaternions.jl implementation uses the renormalize option (but its a bit broken)

Thoughts? @andyferris @c42f

**Comment by c42f** [comment]
Ugh.  Slightly lower cost than renormalizing might be to compute `2*atan2(sqrt(q.v1^2+q.v2^2+q.v3^2), q.s)`?  See http://math.stackexchange.com/questions/291110/numerically-stable-extraction-of-axis-angle-from-unit-quaternion for some more discussion.
