### ISSUE TITLE
Handling the `eye` change

### ISSUE THREAD

**Issue by tkoolen** [FugroRoames/Rotations.jl#62]
What should we do with stuff like

```julia
@inline eye(::Type{AngleAxis}) = AngleAxis(0.0, 1.0, 0.0, 0.0)
@inline eye(::Type{AngleAxis{T}}) where {T} = AngleAxis{T}(zero(T), one(T), zero(T), zero(T))
```
?

The annoying thing is that `UniformScaling` is 'too general': what should we do with `AngleAxis(3.0I)`?

**Comment by andyferris** [comment]
> What should we do with `AngleAxis(3.0I)`?

Well, exactly the same thing as when we `convert` a non-orthogonal 3x3 `Matrix` to  `AngleAxis`, I suppose?

**Comment by andyferris** [comment]
IMO I think that `one(AngleAxis)` and `one(AngleAxis{T})` should be the interface most rotations users would want and use - the identity rotation. We can also support `AngleAxis{T}(I)`.
