### ISSUE TITLE
Broken function: isrotation 

### ISSUE THREAD

**Issue by bhalonen** [FugroRoames/Rotations.jl#78]
In the isrotation function for a 3x3 matrix there is a typo in the indexing to specify the transpose correctly.

I have the obvious quick fix incoming.

https://github.com/FugroRoames/Rotations.jl/blob/7b443f7c4ed9e64c05939e6fde41123fe6f43a86/src/core_types.jl#L145

**Comment by bhalonen** [comment]
@timholy I'm sure this is a typo...

**Comment by timholy** [comment]
Yep, looks like it. Thanks!

**Comment by andyferris** [comment]
Thanks.

I'm slightly surprised this one passed us by...
