### ISSUE TITLE
Testing for proper rotation.

### ISSUE THREAD

**Issue by bhalonen** [FugroRoames/Rotations.jl#80]
Should ```isrotation``` test if the rotation is proper? There is an assumption that rotations can be converted between many reference frames, some of which cannot handle reflection.

The change is simple: test if the determinate is positive.

**Comment by tkoolen** [comment]
I'd say yes, but I don't currently use this functionality myself.

**Comment by bhalonen** [comment]
@tkoolen considering that it didn't work until yesterday, I doubt anyone else besides me is calling it.

**Comment by tkoolen** [comment]
Fixed in #83.
