### ISSUE TITLE
Rotations.RodriguesVec 

### ISSUE THREAD

**Issue by zsz00** [FugroRoames/Rotations.jl#86]
julia : `Rotations.RodriguesVec`  and  python: `rvecs_matrix = cv2.Rodrigues(rvecs, None)`   answer  is different 

julia: 

```julia
using Rotations, StaticArrays
rot_1 = [0.999788  0.003629  -0.020254;  23.244938  -0.003697  0.999988 ; -0.003359  -0.077094  0.020242]
rot_1 = RotMatrix{3, Float64}(rot_1)
rv = RodriguesVec(rot_1)      # -0.137432, -0.00215575, 2.96551
```

python:

```python
import cv2
import numpy as np
rot_1 = np.array([[0.999788, 0.003629, -0.020254],
                      [23.244938, -0.003697, 0.999988],
                      [-0.003359, -0.077094, 0.020242]])
rv= cv2.Rodrigues(rot_1 , None)   # [[-1.16185012], [-1.06024884], [1.1998094]]
```
can you help me, check it out .  thank you!!

**Comment by PaulBellette** [comment]
Call me crazy but I don't think that matrix is a rotation matrix...

**Comment by tkoolen** [comment]
(@zsz00, I took the liberty of formatting your code).

**Comment by tkoolen** [comment]
@PaulBellette is right. @zsz00, what are you expecting this operation to do for the given input matrix?

**Comment by zsz00** [comment]
the rot_1 matrix is a camera rvecs_matrix, i want to transit to a vector.. the rvecs_matrix must be a rotation matrix ??

**Comment by andyferris** [comment]
Can you explain what rvecs are meant to be?

**Comment by PaulBellette** [comment]
I'm not quite sure what you mean, maybe it is a camera matrix? Like you might get from open cv's camera calibration methods? If so they are usually the composition of the camera intrinsic and extrinsic matrices. The extrinsic matrix is an affine matrix made from the translation and rotation of the camera, you might be expecting this function to go from the extrinsic matrix to the rodrigues vector? If so you need something a little different than what this function does. This just goes from a rotation represented as a rotation matrix to the rotation vector.

**Comment by zsz00** [comment]
rvecs_matrix  is a camera matrix,  a camera Rotating matrix , a camera external parameter.

**Comment by tkoolen** [comment]
OK, from https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html:

> rvecs – Output vector of rotation vectors (see Rodrigues() ) estimated for each pattern view (e.g. std::vector<cv::Mat>>). That is, each k-th rotation vector together with the corresponding k-th translation vector (see the next output parameter description) brings the calibration pattern from the model coordinate space (in which object points are specified) to the world coordinate space, that is, a real position of the calibration pattern in the k-th pattern view (k=0.. M -1).

And from https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#void%20Rodrigues(InputArray%20src,%20OutputArray%20dst,%20OutputArray%20jacobian), it appears that the `cv2.Rodrigues` function can be used both to go from a rotation matrix to a rotation vector **as well as the other way around**.

In Rotations.jl, `RodriguesVec` and `RotMatrix` are types. `RodriguesVec(x)` can *only* be used to construct a `RodriguesVec` object (rotation vector) from a value `x` (some other representation of rotation), *not the other way around*. So you probably want:

```julia
using Rotations
rvecs = (RodriguesVec(0.999788, 0.003629, -0.020254),
         RodriguesVec(23.244938, -0.003697, 0.999988),
         RodriguesVec(-0.003359, -0.077094, 0.020242)) # three separate rotation vectors.
rotmatrices = RotMatrix.(rvecs) # three separate rotation matrices, corresponding to the three rotation vectors.
```

**Comment by zsz00** [comment]
thank you , i undersdand it . 

my rvecs is a wrong Rotating matrix.  i get a right Rotating matrix,  and verificated 
 julia : Rotations.RodriguesVec and python: rvecs_matrix = cv2.Rodrigues(rvecs, None) answer is equal..

I am too careless.
