### ISSUE TITLE
RodriguesVec -> RotMatrix problems

### ISSUE THREAD

**Issue by c42f** [FugroRoames/Rotations.jl#9]
The conversion from RodriguresVec to RotMatrix seems a bit off when wrapping past `2π`.  Demo - the following are the same:

```
julia> RotMatrix(RodriguesVec(2π+0.1,0,0))
FixedSizeArrays.Mat{3,3,Float64}(
    1.0 0.0 0.0
    0.0 0.9950041652780258 0.09983341664682784
    0.0 -0.09983341664682784 0.9950041652780258
)

julia> RotMatrix(RodriguesVec(2π-0.1,0,0))
FixedSizeArrays.Mat{3,3,Float64}(
    1.0 0.0 0.0
    0.0 0.9950041652780258 0.09983341664682782
    0.0 -0.09983341664682782 0.9950041652780258
)
```

**Comment by andyferris** [comment]
I'm seeing a questionable `abs` in `rodrigues_to_quat()` [here](https://github.com/FugroRoames/Rotations.jl/blob/master/src/rotation_conversions.jl#L264)

Andrew?

**Comment by awbsmith** [comment]
Removing its fine; it was part of the do I let the axis flip indecision. This should be fixed in the latest PR.

**Comment by c42f** [comment]
This is fixed :-)
